# Generated by Django 4.1.7 on 2023-03-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='n_user',
        ),
    ]
