# Generated by Django 4.0.5 on 2023-03-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_user_customer_n_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='avatar',
            field=models.ImageField(default=True, upload_to='avatar'),
        ),
    ]
